In [1]:
import numpy as np
import pandas as pd

In [2]:
n_val_df    = pd.read_csv('df/n_val_df.csv',index_col = [0,1]) 
n_phasor_df = pd.read_csv('df/n_phasor_df.csv',index_col = [0,1])
n_info_df   = pd.read_csv('df/n_info_df.csv',index_col = [0,1])
n_par_df    = pd.read_csv('df/n_par_df.csv',index_col = [0,1,2])

In [24]:
def getFvalue(the_df): #### Reads the dataframe and gives F-value as a numpy array
    std_val_df = the_df.groupby(level=0).std()
    mean_val_df = the_df.groupby(level=0).mean()
    std_val_df = std_val_df.drop('A1', axis=1)
    mean_val_df = mean_val_df.drop('A1', axis=1)
    std_over_tau_df = (std_val_df/mean_val_df)#/(10**9)
    std_over_tau_arr = np.array(std_over_tau_df)
    std_over_tau1,std_over_tau2=np.split(std_over_tau_arr,2,axis=1)
    n_photon_arr = np.logspace(4,9,20).astype(int) #### Assuming phasor using same number of photons
    F_tau1 = []
    F_tau2 = []
    for i in range(0,20):
        F_tau1.append(std_over_tau1[i] * np.sqrt(n_photon_arr[i]))
        F_tau2.append(std_over_tau2[i] * np.sqrt(n_photon_arr[i]))
    return F_tau1 , F_tau2

In [43]:
F_tau1_not_phasor , F_tau2_not_phasor = getFvalue(n_val_df)
F_tau1_phasor , F_tau2_phasor = getFvalue(n_phasor_df)

In [49]:
F_tau2_phasor ## Just type whatever F_value you want

[array([6.41480749]),
 array([7.02430702]),
 array([9.18557472]),
 array([10.13590275]),
 array([8.95559142]),
 array([10.27515689]),
 array([7.98939899]),
 array([7.84927109]),
 array([7.53179918]),
 array([8.31403039]),
 array([8.66292247]),
 array([8.95595746]),
 array([7.82119185]),
 array([7.4205654]),
 array([8.30298445]),
 array([8.84876166]),
 array([9.23344351]),
 array([8.19617349]),
 array([8.55866388]),
 array([7.43414127])]